### ISSUE TITLE
SQL: pg_switch_wal()

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta_ext#4]
Create a wrapper function for the `pg_switch_wal()` function, or functionality

https://pgpedia.info/p/pg_switch_wal.html

**Comment by GuChad369** [comment]
This will create a function similar to `pgmoneta_switch_wal_ext`, which will behave like `pg_switch_wal()`. Therefore, we just need to define this function so that it executes `pg_switch_wal()` when a user calls `pgmoneta_switch_wal_ext`. 

Is this idea correct, as outlined below?

``` sql
CREATE OR REPLACE FUNCTION pgmoneta_switch_wal_ext() RETURNS TEXT AS $$
DECLARE
    result TEXT;
BEGIN
    result := pg_switch_wal();
    RETURN result;
END;
$$ LANGUAGE plpgsql;
```

**Comment by jesperpedersen** [comment]
I would investigate both options - calling it from lib.c and calling it from .sql as you wrote.

Its `pgmoneta_ext_switch_wal`

**Comment by jesperpedersen** [comment]
We might want to have more functionality associated with the call, so maybe the lib.c way is the best one
