### ISSUE TITLE
Initial test suite

### ISSUE THREAD

**Issue by jesperpedersen** [pgmoneta/pgmoneta_ext#9]
Create a test suite that installs PostgreSQL, the extension, the default pgmoneta role and then executes the functions in the API extension

**Comment by GuChad369** [comment]
Should we create a GitHub workflow `ci.yml` or just a single script file?

**Comment by jesperpedersen** [comment]
Ideally we should be able to run it locally, you can look at what PostgreSQL does, or frameworks like https://libcheck.github.io/check/index.html

Of course it has to run on GitHub as well, so a `ci.yml` is necessary

**Comment by hzhang-vibrant** [comment]
FYI we found [check](https://libcheck.github.io/check/index.html) in [libart](https://github.com/armon/libart/tree/master/tests). It looks pretty straight forward, so maybe you could refer to this. If you have better ideas let us know.

**Comment by Jubilee101** [comment]
FYI we found [check](https://libcheck.github.io/check/index.html) in [libart](https://github.com/armon/libart/tree/master/tests). It looks pretty straight forward, so maybe you could refer to this. If you have better ideas let us know.

**Comment by GuChad369** [comment]
I tested it and found that `check` works better after all dependencies are installed. It is not designed for installation or configuration, as it runs all tests simultaneously. 

However, I want it to run tests one by one as we install all dependencies.

Therefore, the solution is to first use a shell to download and set up all dependencies, and then use `check` to test all API extensions. 

Or we can just use one shell file to do everything. Which option would you prefer?
